RoboBraille.WebApi/Models/Job.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace RoboBraille.WebApi.Models
{
    /// <summary>
    /// Base class for all Jobs
    /// </summary>
    public abstract class Job
    {
        [JsonIgnore]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }


        [JsonIgnore]
        [Required]
        [ForeignKey("User")]
        public Guid UserId { get; set; }


        [JsonIgnore]
        [Required]
        [StringLength(512)]
        public string FileName { get; set; }

        [JsonIgnore]
        [Required]
        [StringLength(512)]
        public string FileExtension { get; set; }

        [JsonIgnore]
        [Required]
        public string MimeType { get; set; }


        [JsonIgnore]
        [Required]
        public JobStatus Status { get; set; }


        [JsonIgnore]
        [Required]
        [DataType(DataType.DateTime)]
        public DateTime SubmitTime { get; set; }


        [JsonIgnore]
        [Required]
        [DataType(DataType.DateTime)]
        public DateTime FinishTime { get; set; }

        /// <summary>
        /// File to be uploaded
        /// </summary>

        //[Required]
        [NotMapped]
        [DataType(DataType.Upload)]
        public byte[] FileContent { get; set; }

        [JsonIgnore]
        public byte[] InputFileHash { get; set; }

        [JsonIgnore]
        public byte[] ResultContent { get; set; }

        [JsonIgnore]
        public virtual ServiceUser User { get; set; }

        //added 03.12.2015
        [JsonIgnore]
        public int DownloadCounter { get; set; }

        [JsonIgnore]
        public string ResultFileExtension { get; set; }

        [JsonIgnore]
        public string ResultMimeType { get; set; }

        public Job()
        {
            SubmitTime = DateTime.Now;
            FinishTime = DateTime.Now;
            DownloadCounter = 0;
        }
    }
}

RoboBraille.WebApi/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RoboBraille.WebApi.Models;

namespace RoboBraille.WebApi.Controllers
{
    public class JobsController : Controller
    {
        private RoboBrailleDataContext db = new RoboBrailleDataContext();

        // GET: Jobs
        public async Task<ActionResult> Index()
        {
            Guid usersjobs = Guid.Empty;
            string sessionUserId = "";
            if (Session["userid"] != null)
                sessionUserId = Session["userid"].ToString();
            if (Guid.TryParse(sessionUserId, out usersjobs))
            {
                var jobs = db.Jobs.Include(j => j.User).Where(j => j.UserId == usersjobs);
                return View(await jobs.ToListAsync());
            } else
            {
                return View(new List<Job>());
            }
        }

        // GET: Jobs based on UserId
        [HttpPost]
        public async Task<ActionResult> Index(string UserId)
        {
            Guid usersjobs = Guid.Empty;
            if (!string.IsNullOrWhiteSpace(UserId))
            {
                if (Guid.TryParse((string) UserId, out usersjobs))
                {
                    Session["UserId"] = UserId;
                    var jobs = db.Jobs.Include(j => j.User).Where(j => j.UserId == usersjobs).OrderByDescending(j => j.FinishTime);
                    return View(await jobs.ToListAsync());
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
            } else
            {
                var jobs = db.Jobs.Include(j => j.User).Where(j => j.UserId == usersjobs);
                return View(await jobs.ToListAsync());
            }
        }

        // GET: Jobs/Details/5
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = await db.Jobs.FindAsync(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // GET: Jobs/Delete/5
        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = await db.Jobs.FindAsync(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            Job job = await db.Jobs.FindAsync(id);
            db.Jobs.Remove(job);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RoboBraille.WebApi/Views/Jobs/Delete.cshtml
@model RoboBraille.WebApi.Models.Job

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Job</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileExtension)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileExtension)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MimeType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MimeType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubmitTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubmitTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FinishTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FinishTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InputFileHash)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InputFileHash)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DownloadCounter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DownloadCounter)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResultFileExtension)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResultFileExtension)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResultMimeType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResultMimeType)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RoboBraille.WebApi/Views/Jobs/Details.cshtml
@model RoboBraille.WebApi.Models.Job

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Job</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileExtension)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileExtension)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MimeType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MimeType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubmitTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubmitTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FinishTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FinishTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InputFileHash)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InputFileHash)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.DownloadCounter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DownloadCounter)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResultFileExtension)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResultFileExtension)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResultMimeType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResultMimeType)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Delete", "Delete", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RoboBraille.WebApi/Views/Jobs/Index.cshtml
@model IEnumerable<RoboBraille.WebApi.Models.Job>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@if (Session["role"] != null && (int)Session["role"]==1)
{
    <p>
        <!--Input your userID here-->
        @using (Html.BeginForm("Index", "Jobs", FormMethod.Post))
        {
            <label for="userid">Enter User ID</label>
            <input id="UserId" name="UserId" type="text" />
            <button type="submit" id="getJobs">Submit</button>
        }
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FileName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubmitTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FinishTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DownloadCounter)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FileName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubmitTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FinishTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DownloadCounter)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>